fix(build): check for keywords to fail workflow (#588)

diff --git a/.github/workflows/prod_push_update_to_server.yml b/.github/workflows/prod_push_update_to_server.yml
--- a/.github/workflows/prod_push_update_to_server.yml
+++ b/.github/workflows/prod_push_update_to_server.yml
@@ -41,3 +41,11 @@ jobs:
         port: ${{ env.ACTION_GXFS_WEBSERVER_SSH_PORT }}
         script: |
                     ./gtfs_org_website_updater.sh
+
+    - name: Check for errors in the output
+      run: |
+        if grep -i -e "error" -e "fatal" -e "exception" -e "fail" -e "critical" -e "segfault" -e "panic" -e "abort" -e "unable" -e "invalid" -e "stack trace" -e "segmentation fault" -e "timeout" -e "missing" -e "not found" -e "permission denied" -e "unsuccessful" -e "could not" -e "fatal error" -e "unsupported" -e "unable to" output.log; then
+          echo "Error found, failing the workflow."
+          exit 1
+        fi
+      continue-on-error: false
